### PR TITLE
Another active one.

### PR DESCRIPTION
**Pull request by samwilson**
With three footnotes (and nothing much else that's special).

### CODE REVIEW

**Comment by samwilson** [comment]
Thanks! :)

**Comment by sethwoodworth** [comment]
Although, you should know that we are working on a release of 50 books by the end of the week and are keeping track of them on [this spreadsheet in the Second-Folio](https://github.com/gitenberg-dev/Second-Folio/blob/f636fe7d6a13e7f0675eed4b4ec59adf3b9dfa4c/Gitenberg%20Book%20List.csv) repo.

**Comment by sethwoodworth** [comment]
As soon as this is done, we'll add these 50 books to this spreadsheet too

**Comment by samwilson** [comment]
Ah cool :) thanks, i'll have a read of some of them too!

**Pull request merged**
